server:
  port: 8082

spring:
  boot:
    admin:
      client:
        # admin-server-url: 必须加上 协议名称.
        url: http://localhost:8081  # admin-server 地址
  mvc:
    servlet:
      path: /client

# 暴露端点.
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
