server:
  port: 8081
spring:
  boot:
    admin:
      client:
        # admin-server-url: 必须加上 协议名称.
        url: http://localhost:8080
# 暴露端点.
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
