# 1. 添加依赖
# 2. 开放节点



management:
  endpoint:
    env:
      enabled: true
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'  # 默认只开放, info 节点, "*"

spring:
  security:
    user:
      name: child # 默认 user.
      password: child  # 不设值就自动生成 UUID.

server:
  port: 9000

logging:
  level:
    root: info


