spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://120.78.70.187:3306/upush_center?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root
  #    schema:
  #      - sql/
  #
  #    initialization-mode: always
  #  关于视图解析器: 代码的视图解析优先于配置文件(同时配置的话, 配置文件会被覆盖), 详见 com.xq.live.upush.config.SwaggerConfig
  #  mvc:
  #    view:
  #      prefix: /WEB-INF/jsp/
  #      suffix: .jsp
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true


#mybatis:
#  mapper-locations:
