# thymeleaf
spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false # 禁用缓存, 修改之后立即生效
  mvc:
    # 日志展示详细信息: org.springframework.web.servlet.FrameworkServlet.setEnableLoggingRequestDetails
    # org.springframework.web.servlet.FrameworkServlet#initServletBean
    log-request-details: true

# ctx
server:
  servlet:
    context-path: /product # 项目访问根路径

debug: on

logging:
  #  pattern:
  #    console: "%d - %msg%n"  # 自定义控制台输出格式
  #    dateformat: "y-MM-dd HH:mm:ss:SSS"
  #    file: "D:/single/log.log"
  # 指定包的 log 级别
  level:
    org.springframework.web: trace
    org.thymeleaf: trace

