
package com.senyint.pacs.serv1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "pacsChannel", targetNamespace = "http://serv.pacs.senyint.com/")
// @XmlSeeAlso({
//     ObjectFactory.class
// })
public interface PacsChannel {


    /**
     * 
     * @param input
     * @param method
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    // @WebResult(targetNamespace = "")
    // @RequestWrapper(localName = "invoke", targetNamespace = "http://serv.pacs.senyint.com/", className = "com.senyint.pacs.serv.Invoke")
    // @ResponseWrapper(localName = "invokeResponse", targetNamespace = "http://serv.pacs.senyint.com/", className = "com.senyint.pacs.serv.InvokeResponse")
    String invoke(
        @WebParam(name = "method", targetNamespace = "")
        String method,
        @WebParam(name = "input", targetNamespace = "")
        String input)
    ;

}
